# Generated by Django 4.2.2 on 2023-09-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Проверен модератором'),
        ),
    ]
